### ISSUE TITLE
Gitignore ingoriert SteamVR settings nicht

### ISSUE THREAD

**Issue by HATZ01** [4ahmnm2021-G3-G4/01-maze-audiocode-HATZ01#1]
Obwohl SteamVR und die zugehörigen Ordner im Gitignore stehen werden sie beim commiten nicht ingoriert.

**Comment by HATZ01** [comment]
@smeerws

**Comment by smeerws** [comment]
im 2ten commit hast du 
Assets/SteamVR.meta
Assets/SteamVR_Resources.meta
zum Tracken begonnen. Die müssen raus aus dem Tracking. 

Untrack files already added to git repo: 
git rm -r --cached fileToUntrack.meta

rm is the remove command
-r will allow recursive removal
--cached will only remove files from the index. Your files will still be there.

**Comment by HATZ01** [comment]
@smeerws Der Befehl führt bei mir zu folgender Fehlermeldung:

fatal: pathspec 'SteamVR.meta' did not match any files

Liegt das daran, dass ich immer noch im whiteboxing branch arbeite? Muss ich dafür in den main branch wechseln?

**Comment by smeerws** [comment]
wie genau war der Befehl du musst den ganzen Pfad relativ angeben, so wie er halt mit git status ausgegeben wird

**Comment by HATZ01** [comment]
Ich hab den Pfad aus der git status Ausgabe kopiert.

**Comment by smeerws** [comment]
magst du mir bitte nochmal das ausführen und  mir von der console einen screenshot hier reingeben. git status, git rm -r --cached fileToUntrack.meta 
Danke

**Comment by smeerws** [comment]
Reihenfolge ändern:

folgende Zeilen 

# Asset meta data should only be ignored when the corresponding asset is also ignored
!/[Aa]ssets/**/*.meta

vor  

/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Mm]emoryCaptures/

schreiben. 
Bei mir löst dies das Problem.
