### ISSUE TITLE
Nach Änderung an der Scene kein pushen möglich

### ISSUE THREAD

**Issue by HATZ01** [4ahmnm2021-G3-G4/01-maze-audiocode-HATZ01#2]
@smeerws 

Ich wollte, nachdem ich meine anderen Tracking-Sounds testweise hinzugefügt habe einmal commiten. Allerdings lässt mich das Projekt die Änderungen nicht pushen. Dabei erscheint folgende Meldung:

hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Im Anhang auch nochmal ein Screenshot von meinem Terminal.
<img width="721" alt="Fehler_Git_Push" src="https://user-images.githubusercontent.com/56028836/118445647-ff804480-b6ee-11eb-8beb-317b146be5a0.png">

**Comment by smeerws** [comment]
du hast online was geändert, was lokal noch nicht berücksichtigt wurde. Lese den gelben Teil da wo hint steht. Zuerst git pull. Ich schätze das Readme wurde geändert. dann kannst du comitten

**Comment by HATZ01** [comment]
Da kommt dann folgendes:

Noah-Hatz-MacBook:01-maze-audiocode-HATZ01 Noah$ git pull
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

Soll ich die beiden branches wirklich schon mergen?

**Comment by HATZ01** [comment]
Ah, jetzt hat's geklappt. Danke!
